 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/run1/dommani:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/run1/dommani:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
 - args: ['compute', 'instances', 'update-container', 'wb-2', '--zone', 'asia-south1-c', '--container-image=us-central1-docker.pkg.dev/$PROJECT_ID/run1/dommani:$COMMIT_SHA']
images:
 - 'us-central1-docker.pkg.dev/$PROJECT_ID/run1/dommani:$COMMIT_SHA'
