---
- name: Docker-Playbook
- hosts: 127.0.0.1
  tasks:
  - name: Install docker.
    package:
      name: docker-ce
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
