---
- name: Docker-Playbook
  hosts: 127.0.0.1
  become: true
  become_method: su
  tasks:
  - name: Install docker
    package:
      name: docker.io
      state: present
  - name: Start docker service
    service:
      name: docker
      state: started
